// _CreationController_EOArchive.java
// Generated by EnterpriseObjects palette at lundi 28 novembre 2011 16 h 42 Europe/Paris

package org.cocktail.groupescol.client;

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.eointerface.swing.EOTable._EOTableColumn;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _CreationController_EOArchive extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eocontrol.EODataSource _eoDataSource0, _eoDataSource1, _eoDataSource2, _eoDataSource3;
    com.webobjects.eocontrol.EOEditingContext _eoEditingContext0;
    com.webobjects.eointerface.EODisplayGroup _eoDisplayGroup0, _eoDisplayGroup1, _eoDisplayGroup2, _eoDisplayGroup3;
    com.webobjects.eointerface.EOTableAssociation _eoTableAssociation0, _eoTableAssociation1, _eoTableAssociation2, _eoTableAssociation3;
    com.webobjects.eointerface.EOTableColumnAssociation _eoTableColumnAssociation0, _eoTableColumnAssociation1, _eoTableColumnAssociation10, _eoTableColumnAssociation11, _eoTableColumnAssociation12, _eoTableColumnAssociation13, _eoTableColumnAssociation14, _eoTableColumnAssociation15, _eoTableColumnAssociation16, _eoTableColumnAssociation2, _eoTableColumnAssociation3, _eoTableColumnAssociation4, _eoTableColumnAssociation5, _eoTableColumnAssociation6, _eoTableColumnAssociation7, _eoTableColumnAssociation8, _eoTableColumnAssociation9;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOTable _nsTableView0, _nsTableView1, _nsTableView2, _nsTableView3;
    com.webobjects.eointerface.swing.EOTable._EOTableColumn _eoTableColumn0, _eoTableColumn1, _eoTableColumn10, _eoTableColumn11, _eoTableColumn12, _eoTableColumn13, _eoTableColumn14, _eoTableColumn15, _eoTableColumn16, _eoTableColumn2, _eoTableColumn3, _eoTableColumn4, _eoTableColumn5, _eoTableColumn6, _eoTableColumn7, _eoTableColumn8, _eoTableColumn9;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField2, _nsTextField3, _nsTextField4;
    com.webobjects.eointerface.swing.EOView _nsBox0;
    com.webobjects.foundation.NSNumberFormatter _nsNumberFormatter0, _nsNumberFormatter1, _nsNumberFormatter10, _nsNumberFormatter2, _nsNumberFormatter3, _nsNumberFormatter4, _nsNumberFormatter5, _nsNumberFormatter6, _nsNumberFormatter7, _nsNumberFormatter8, _nsNumberFormatter9;
    java.awt.Container _nsCustomView0;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton10, _nsButton11, _nsButton2, _nsButton3, _nsButton4, _nsButton5, _nsButton6, _nsButton7, _nsButton8, _nsButton9;
    javax.swing.JCheckBox _nsButton12;
    javax.swing.JComboBox _popup0;
    javax.swing.JPanel _nsView0;

    public _CreationController_EOArchive(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField221");
        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField22");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bSupprGrp")) != null)) {
            _nsButton11 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton11");
        } else {
            _nsButton11 = (javax.swing.JButton)_registered(new javax.swing.JButton("Supprimer le groupe"), "NSButton1212");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bCreerGrp")) != null)) {
            _nsButton10 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton10");
        } else {
            _nsButton10 = (javax.swing.JButton)_registered(new javax.swing.JButton("Ajouter un groupe"), "NSButton1211");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bInclureND")) != null)) {
            _nsButton9 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton9");
        } else {
            _nsButton9 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cr\u00e9er Collection"), "NSButton132");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bModifGrp")) != null)) {
            _nsButton8 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton8");
        } else {
            _nsButton8 = (javax.swing.JButton)_registered(new javax.swing.JButton("Modifier le groupe"), "NSButton121");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bGrpAp")) != null)) {
            _nsButton7 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton7");
        } else {
            _nsButton7 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cr\u00e9er Collection"), "NSButton1121");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "comboTypeEc")) != null)) {
            _popup0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup0");
        } else {
            _popup0 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "cEcLibre")) != null)) {
            _nsButton12 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton12");
        } else {
            _nsButton12 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("EC Libre"), "NSButton4");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bDesinclure")) != null)) {
            _nsButton6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton6");
        } else {
            _nsButton6 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cr\u00e9er Collection"), "NSButton131");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bInclure")) != null)) {
            _nsButton5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton5");
        } else {
            _nsButton5 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cr\u00e9er Collection"), "NSButton13");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bModifCol")) != null)) {
            _nsButton4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton4");
        } else {
            _nsButton4 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cr\u00e9er Collection"), "NSButton12");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bSelectAllAp")) != null)) {
            _nsButton3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton3");
        } else {
            _nsButton3 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton111");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bFetchAllAp")) != null)) {
            _nsButton2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton2");
        } else {
            _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cr\u00e9er Collection"), "NSButton11");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "typeApSeuilContainer")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (java.awt.Container)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (java.awt.Container)_registered(new java.awt.Container(), "View");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bSupprCol")) != null)) {
            _nsButton1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton1");
        } else {
            _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cr\u00e9er Collection"), "NSButton1");
        }

        _nsNumberFormatter10 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0;-0"), "");
        _eoTableColumn16 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tableCollection")) != null)) {
            _nsTableView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView0");
        } else {
            _nsTableView0 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "");
        }

        _eoTableColumnAssociation16 = (com.webobjects.eointerface.EOTableColumnAssociation)_registered(new com.webobjects.eointerface.EOTableColumnAssociation(_eoTableColumn16, _nsTableView0), "");
        _nsNumberFormatter9 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0;-0"), "");
        _eoTableColumn15 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumnAssociation15 = (com.webobjects.eointerface.EOTableColumnAssociation)_registered(new com.webobjects.eointerface.EOTableColumnAssociation(_eoTableColumn15, _nsTableView0), "");
        _eoTableAssociation3 = (com.webobjects.eointerface.EOTableAssociation)_registered(new com.webobjects.eointerface.EOTableAssociation(_nsTableView0), "");
        _nsNumberFormatter8 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0;-0"), "");
        _eoTableColumn14 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tableGroupeInclusion")) != null)) {
            _nsTableView3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView3");
        } else {
            _nsTableView3 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "");
        }

        _eoTableColumnAssociation14 = (com.webobjects.eointerface.EOTableColumnAssociation)_registered(new com.webobjects.eointerface.EOTableColumnAssociation(_eoTableColumn14, _nsTableView3), "");
        _nsNumberFormatter7 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0;-0"), "");
        _eoTableColumn13 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumnAssociation13 = (com.webobjects.eointerface.EOTableColumnAssociation)_registered(new com.webobjects.eointerface.EOTableColumnAssociation(_eoTableColumn13, _nsTableView3), "");
        _eoTableColumn12 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumnAssociation12 = (com.webobjects.eointerface.EOTableColumnAssociation)_registered(new com.webobjects.eointerface.EOTableColumnAssociation(_eoTableColumn12, _nsTableView3), "");
        _nsNumberFormatter6 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0;-0"), "");
        _eoTableColumn11 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumnAssociation11 = (com.webobjects.eointerface.EOTableColumnAssociation)_registered(new com.webobjects.eointerface.EOTableColumnAssociation(_eoTableColumn11, _nsTableView3), "");
        _eoTableColumn10 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumnAssociation10 = (com.webobjects.eointerface.EOTableColumnAssociation)_registered(new com.webobjects.eointerface.EOTableColumnAssociation(_eoTableColumn10, _nsTableView3), "");
        _eoTableAssociation2 = (com.webobjects.eointerface.EOTableAssociation)_registered(new com.webobjects.eointerface.EOTableAssociation(_nsTableView3), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "eodGroupeInclusion")) != null)) {
            _eoDisplayGroup3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.EODisplayGroup)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoDisplayGroup3");
        } else {
            _eoDisplayGroup3 = (com.webobjects.eointerface.EODisplayGroup)_registered(new com.webobjects.eointerface.EODisplayGroup(), "ScolGroupeInclusion");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "editingContext")) != null)) {
            _eoEditingContext0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eocontrol.EOEditingContext)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoEditingContext0");
        } else {
            _eoEditingContext0 = ((com.webobjects.eocontrol.EOEditingContext.substitutionEditingContext() != null) ? com.webobjects.eocontrol.EOEditingContext.substitutionEditingContext() : (com.webobjects.eocontrol.EOEditingContext)_registered(new com.webobjects.eocontrol.EOEditingContext(), "EditingContext"));
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "eodGroupeInclusion.dataSource")) != null)) {
            _eoDataSource3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eocontrol.EODataSource)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoDataSource3");
        } else {
            _eoDataSource3 = (com.webobjects.eocontrol.EODataSource)_registered(com.webobjects.eoapplication.EODataSourceFactory.defaultDataSourceFactory().newMasterDataSource(_eoEditingContext0, "ScolGroupeInclusion", null), "DataSource");
        }

        _nsNumberFormatter5 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0;-0"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tableMaquetteAp")) != null)) {
            _nsTableView2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView2");
        } else {
            _nsTableView2 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "");
        }

        _eoTableAssociation1 = (com.webobjects.eointerface.EOTableAssociation)_registered(new com.webobjects.eointerface.EOTableAssociation(_nsTableView2), "");
        _nsNumberFormatter4 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0;-0"), "");
        _eoTableColumn9 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumnAssociation9 = (com.webobjects.eointerface.EOTableColumnAssociation)_registered(new com.webobjects.eointerface.EOTableColumnAssociation(_eoTableColumn9, _nsTableView2), "");
        _nsNumberFormatter3 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0;-0"), "");
        _eoTableColumn8 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumnAssociation8 = (com.webobjects.eointerface.EOTableColumnAssociation)_registered(new com.webobjects.eointerface.EOTableColumnAssociation(_eoTableColumn8, _nsTableView2), "");
        _eoTableColumn7 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumnAssociation7 = (com.webobjects.eointerface.EOTableColumnAssociation)_registered(new com.webobjects.eointerface.EOTableColumnAssociation(_eoTableColumn7, _nsTableView2), "");
        _eoTableColumn6 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumnAssociation6 = (com.webobjects.eointerface.EOTableColumnAssociation)_registered(new com.webobjects.eointerface.EOTableColumnAssociation(_eoTableColumn6, _nsTableView2), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "eodMaquetteAp")) != null)) {
            _eoDisplayGroup2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.EODisplayGroup)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoDisplayGroup2");
        } else {
            _eoDisplayGroup2 = (com.webobjects.eointerface.EODisplayGroup)_registered(new com.webobjects.eointerface.EODisplayGroup(), "ScolMaquetteAp");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "eodMaquetteAp.dataSource")) != null)) {
            _eoDataSource2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eocontrol.EODataSource)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoDataSource2");
        } else {
            _eoDataSource2 = (com.webobjects.eocontrol.EODataSource)_registered(com.webobjects.eoapplication.EODataSourceFactory.defaultDataSourceFactory().newMasterDataSource(_eoEditingContext0, "ScolMaquetteAp", null), "DataSource");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tableGroupeGrp")) != null)) {
            _nsTableView1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView1");
        } else {
            _nsTableView1 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "");
        }

        _eoTableAssociation0 = (com.webobjects.eointerface.EOTableAssociation)_registered(new com.webobjects.eointerface.EOTableAssociation(_nsTableView1), "");
        _nsNumberFormatter2 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0;-0"), "");
        _eoTableColumn5 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumnAssociation5 = (com.webobjects.eointerface.EOTableColumnAssociation)_registered(new com.webobjects.eointerface.EOTableColumnAssociation(_eoTableColumn5, _nsTableView1), "");
        _nsNumberFormatter1 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0;-0"), "");
        _eoTableColumn4 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumnAssociation4 = (com.webobjects.eointerface.EOTableColumnAssociation)_registered(new com.webobjects.eointerface.EOTableColumnAssociation(_eoTableColumn4, _nsTableView1), "");
        _eoTableColumn3 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumnAssociation3 = (com.webobjects.eointerface.EOTableColumnAssociation)_registered(new com.webobjects.eointerface.EOTableColumnAssociation(_eoTableColumn3, _nsTableView1), "");
        _nsNumberFormatter0 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0;-0"), "");
        _eoTableColumn2 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumnAssociation2 = (com.webobjects.eointerface.EOTableColumnAssociation)_registered(new com.webobjects.eointerface.EOTableColumnAssociation(_eoTableColumn2, _nsTableView1), "");
        _eoTableColumn1 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumnAssociation1 = (com.webobjects.eointerface.EOTableColumnAssociation)_registered(new com.webobjects.eointerface.EOTableColumnAssociation(_eoTableColumn1, _nsTableView1), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "eodGrpGroupe")) != null)) {
            _eoDisplayGroup1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.EODisplayGroup)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoDisplayGroup1");
        } else {
            _eoDisplayGroup1 = (com.webobjects.eointerface.EODisplayGroup)_registered(new com.webobjects.eointerface.EODisplayGroup(), "ScolGroupeGrp");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "eodGrpGroupe.dataSource")) != null)) {
            _eoDataSource1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eocontrol.EODataSource)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoDataSource1");
        } else {
            _eoDataSource1 = (com.webobjects.eocontrol.EODataSource)_registered(com.webobjects.eoapplication.EODataSourceFactory.defaultDataSourceFactory().newMasterDataSource(_eoEditingContext0, "ScolGroupeGrp", null), "DataSource");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "eodCollection.dataSource")) != null)) {
            _eoDataSource0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eocontrol.EODataSource)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoDataSource0");
        } else {
            _eoDataSource0 = (com.webobjects.eocontrol.EODataSource)_registered(com.webobjects.eoapplication.EODataSourceFactory.defaultDataSourceFactory().newMasterDataSource(_eoEditingContext0, "ScolGroupeCollection", null), "DataSource");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "eodCollection")) != null)) {
            _eoDisplayGroup0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.EODisplayGroup)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoDisplayGroup0");
        } else {
            _eoDisplayGroup0 = (com.webobjects.eointerface.EODisplayGroup)_registered(new com.webobjects.eointerface.EODisplayGroup(), "ScolGroupeCollection");
        }

        _eoTableColumn0 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumnAssociation0 = (com.webobjects.eointerface.EOTableColumnAssociation)_registered(new com.webobjects.eointerface.EOTableColumnAssociation(_eoTableColumn0, _nsTableView0), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bCreerCol")) != null)) {
            _nsButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton0");
        } else {
            _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cr\u00e9er Collection"), "NSButton");
        }

        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "component")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "MainWindow");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _nsButton11.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "supprimerGroupe", _nsButton11), ""));

        if (_replacedObjects.objectForKey("_nsButton11") == null) {
            _connect(_owner(), _nsButton11, "bSupprGrp");
        }

        _nsButton10.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "ajouterGroupe", _nsButton10), ""));

        if (_replacedObjects.objectForKey("_nsButton10") == null) {
            _connect(_owner(), _nsButton10, "bCreerGrp");
        }

        _nsButton9.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "inclureNiveauDiplome", _nsButton9), ""));

        if (_replacedObjects.objectForKey("_nsButton9") == null) {
            _connect(_owner(), _nsButton9, "bInclureND");
        }

        _nsButton8.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "modifierGroupe", _nsButton8), ""));

        if (_replacedObjects.objectForKey("_nsButton8") == null) {
            _connect(_owner(), _nsButton8, "bModifGrp");
        }

        _nsButton7.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "afficherGroupesPourAp", _nsButton7), ""));

        if (_replacedObjects.objectForKey("_nsButton7") == null) {
            _connect(_owner(), _nsButton7, "bGrpAp");
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _popup0.setModel(new javax.swing.DefaultComboBoxModel());
            _popup0.addItem("Item1");
            _popup0.addItem("Item2");
            _popup0.addItem("Item3");
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _connect(_owner(), _popup0, "comboTypeEc");
        }

        _nsButton12.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "rechargerAp", _nsButton12), ""));

        if (_replacedObjects.objectForKey("_nsButton12") == null) {
            _connect(_owner(), _nsButton12, "cEcLibre");
        }

        _nsButton6.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "exclure", _nsButton6), ""));

        if (_replacedObjects.objectForKey("_nsButton6") == null) {
            _connect(_owner(), _nsButton6, "bDesinclure");
        }

        _nsButton5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "inclure", _nsButton5), ""));

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _connect(_owner(), _nsButton5, "bInclure");
        }

        _nsButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "modifierCollection", _nsButton4), ""));

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _connect(_owner(), _nsButton4, "bModifCol");
        }

        _nsButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "selectionnerTousLesAps", _nsButton3), ""));

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _connect(_owner(), _nsButton3, "bSelectAllAp");
        }

        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "afficherTousLesAps", _nsButton2), ""));

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _connect(_owner(), _nsButton2, "bFetchAllAp");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "typeApSeuilContainer");
        }

        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "supprimerCollection", _nsButton1), ""));

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _connect(_owner(), _nsButton1, "bSupprCol");
        }

        if (_replacedObjects.objectForKey("_eoDisplayGroup0") == null) {
            _connect(_owner(), _eoDisplayGroup0, "eodCollection");
        }

        if (_replacedObjects.objectForKey("_eoDisplayGroup3") == null) {
            _connect(_owner(), _eoDisplayGroup3, "eodGroupeInclusion");
        }

        if (_replacedObjects.objectForKey("_nsTableView3") == null) {
            _connect(_owner(), _nsTableView3, "tableGroupeInclusion");
        }

        if (_replacedObjects.objectForKey("_eoEditingContext0") == null) {
            _connect(_owner(), _eoEditingContext0, "editingContext");
        }

        if (_replacedObjects.objectForKey("_eoDisplayGroup2") == null) {
            _connect(_owner(), _eoDisplayGroup2, "eodMaquetteAp");
        }

        if (_replacedObjects.objectForKey("_nsTableView2") == null) {
            _connect(_owner(), _nsTableView2, "tableMaquetteAp");
        }

        if (_replacedObjects.objectForKey("_eoDisplayGroup1") == null) {
            _connect(_owner(), _eoDisplayGroup1, "eodGrpGroupe");
        }

        if (_replacedObjects.objectForKey("_nsTableView1") == null) {
            _connect(_owner(), _nsTableView1, "tableGroupeGrp");
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_owner(), _nsTableView0, "tableCollection");
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _connect(_owner(), _nsButton0, "bCreerCol");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "component");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "creerCollection", _nsButton0), ""));
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsTextField4, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField4.setEditable(false);
        _nsTextField4.setOpaque(false);
        _nsTextField4.setText("Groupes inclus :");
        _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField4.setSelectable(false);
        _nsTextField4.setEnabled(true);
        _nsTextField4.setBorder(null);
        _setFontForComponent(_nsTextField3, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField3.setEditable(false);
        _nsTextField3.setOpaque(false);
        _nsTextField3.setText("Collection :");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField3.setSelectable(false);
        _nsTextField3.setEnabled(true);
        _nsTextField3.setBorder(null);
        _setFontForComponent(_nsTextField2, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("Groupes de la collection s\u00e9lectionn\u00e9e ci-contre :");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        _setFontForComponent(_nsTextField1, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("Atomes p\u00e9dagogiques associes :");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField1.setSelectable(false);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);

        if (_replacedObjects.objectForKey("_nsButton11") == null) {
            _setFontForComponent(_nsButton11, "Lucida Grande", 13, Font.PLAIN);
            _nsButton11.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton10") == null) {
            _setFontForComponent(_nsButton10, "Lucida Grande", 13, Font.PLAIN);
            _nsButton10.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton9") == null) {
            _setFontForComponent(_nsButton9, "Lucida Grande", 13, Font.PLAIN);
            _nsButton9.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton8") == null) {
            _setFontForComponent(_nsButton8, "Lucida Grande", 13, Font.PLAIN);
            _nsButton8.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton7") == null) {
            _setFontForComponent(_nsButton7, "Lucida Grande", 13, Font.PLAIN);
            _nsButton7.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _setFontForComponent(_popup0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton12") == null) {
            _setFontForComponent(_nsButton12, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton6") == null) {
            _setFontForComponent(_nsButton6, "Lucida Grande", 13, Font.PLAIN);
            _nsButton6.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _setFontForComponent(_nsButton5, "Lucida Grande", 13, Font.PLAIN);
            _nsButton5.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _setFontForComponent(_nsButton4, "Lucida Grande", 13, Font.PLAIN);
            _nsButton4.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _setFontForComponent(_nsButton3, "Lucida Grande", 13, Font.PLAIN);
            _nsButton3.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _setFontForComponent(_nsButton2, "Lucida Grande", 13, Font.PLAIN);
            _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
            _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        }

        
        _eoTableColumn16.setMinWidth(61);
        _eoTableColumn16.setMaxWidth(1000);
        _eoTableColumn16.setPreferredWidth(144);
        _eoTableColumn16.setWidth(144);
        _eoTableColumn16.setResizable(true);
        _eoTableColumn16.setHeaderValue("Fin validit\u00e9");
        if ((_eoTableColumn16.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn16.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        	_eoTableColumn16.setCellRenderer(renderer);
        }
        _eoTableColumnAssociation16.bindAspect(com.webobjects.eointerface.EOAssociation.ValueAspect, _eoDisplayGroup0, "gcolDateFin");
        if (_eoTableColumnAssociation16.canSupportValueFormatter()) { _eoTableColumnAssociation16.setValueFormatter(_nsNumberFormatter10); }
        _eoTableColumnAssociation16.establishConnection();
        
        _eoTableColumn15.setMinWidth(10);
        _eoTableColumn15.setMaxWidth(1000);
        _eoTableColumn15.setPreferredWidth(116);
        _eoTableColumn15.setWidth(116);
        _eoTableColumn15.setResizable(true);
        _eoTableColumn15.setHeaderValue("D\u00e9but validit\u00e9");
        if ((_eoTableColumn15.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn15.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        	_eoTableColumn15.setCellRenderer(renderer);
        }
        _eoTableColumnAssociation15.bindAspect(com.webobjects.eointerface.EOAssociation.ValueAspect, _eoDisplayGroup0, "gcolDateDebut");
        if (_eoTableColumnAssociation15.canSupportValueFormatter()) { _eoTableColumnAssociation15.setValueFormatter(_nsNumberFormatter9); }
        _eoTableColumnAssociation15.establishConnection();
        _eoTableAssociation3.bindAspect(com.webobjects.eointerface.EOAssociation.SourceAspect, _eoDisplayGroup0, "");
        _eoTableAssociation3.setSortsByColumnOrder(true);
        _eoTableAssociation3.establishConnection();
        
        _eoTableColumnAssociation14.bindAspect(com.webobjects.eointerface.EOAssociation.ValueAspect, _eoDisplayGroup3, "scolGroupeGrpFils.ggrpDateFin");
        if (_eoTableColumnAssociation14.canSupportValueFormatter()) { _eoTableColumnAssociation14.setValueFormatter(_nsNumberFormatter8); }
        _eoTableColumnAssociation14.establishConnection();
        _eoTableColumn14.setMinWidth(67);
        _eoTableColumn14.setMaxWidth(1000);
        _eoTableColumn14.setPreferredWidth(120);
        _eoTableColumn14.setWidth(120);
        _eoTableColumn14.setResizable(true);
        _eoTableColumn14.setHeaderValue("Fin Validit\u00e9");
        if ((_eoTableColumn14.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn14.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        	_eoTableColumn14.setCellRenderer(renderer);
        }
        
        _eoTableColumnAssociation13.bindAspect(com.webobjects.eointerface.EOAssociation.ValueAspect, _eoDisplayGroup3, "scolGroupeGrpFils.ggrpDateDebut");
        if (_eoTableColumnAssociation13.canSupportValueFormatter()) { _eoTableColumnAssociation13.setValueFormatter(_nsNumberFormatter7); }
        _eoTableColumnAssociation13.establishConnection();
        _eoTableColumn13.setMinWidth(10);
        _eoTableColumn13.setMaxWidth(1000);
        _eoTableColumn13.setPreferredWidth(117);
        _eoTableColumn13.setWidth(117);
        _eoTableColumn13.setResizable(true);
        _eoTableColumn13.setHeaderValue("D\u00e9but Validit\u00e9");
        if ((_eoTableColumn13.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn13.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        	_eoTableColumn13.setCellRenderer(renderer);
        }
        _eoTableColumnAssociation12.bindAspect(com.webobjects.eointerface.EOAssociation.ValueAspect, _eoDisplayGroup3, "scolGroupeGrpFils.ggrpLibelle");
        _eoTableColumnAssociation12.establishConnection();
        _eoTableColumn12.setMinWidth(10);
        _eoTableColumn12.setMaxWidth(1000);
        _eoTableColumn12.setPreferredWidth(111);
        _eoTableColumn12.setWidth(111);
        _eoTableColumn12.setResizable(true);
        _eoTableColumn12.setHeaderValue("Libelle");
        _nsNumberFormatter6.setLocalizesPattern(true);
        _eoTableColumnAssociation11.bindAspect(com.webobjects.eointerface.EOAssociation.ValueAspect, _eoDisplayGroup3, "scolGroupeGrpFils.ggrpMaxCapacite");
        if (_eoTableColumnAssociation11.canSupportValueFormatter()) { _eoTableColumnAssociation11.setValueFormatter(_nsNumberFormatter6); }
        _eoTableColumnAssociation11.establishConnection();
        _eoTableColumn11.setMinWidth(10);
        _eoTableColumn11.setMaxWidth(1000);
        _eoTableColumn11.setPreferredWidth(56);
        _eoTableColumn11.setWidth(56);
        _eoTableColumn11.setResizable(true);
        _eoTableColumn11.setHeaderValue("Cap. Max");
        _eoTableColumnAssociation10.bindAspect(com.webobjects.eointerface.EOAssociation.ValueAspect, _eoDisplayGroup3, "scolGroupeGrpFils.ggrpCode");
        _eoTableColumnAssociation10.establishConnection();
        _eoTableColumn10.setMinWidth(10);
        _eoTableColumn10.setMaxWidth(1000);
        _eoTableColumn10.setPreferredWidth(132);
        _eoTableColumn10.setWidth(132);
        _eoTableColumn10.setResizable(true);
        _eoTableColumn10.setHeaderValue("Code");

        if (_replacedObjects.objectForKey("_nsTableView3") == null) {
            _nsTableView3.table().addColumn(_eoTableColumn10);
            _nsTableView3.table().addColumn(_eoTableColumn11);
            _nsTableView3.table().addColumn(_eoTableColumn12);
            _nsTableView3.table().addColumn(_eoTableColumn13);
            _nsTableView3.table().addColumn(_eoTableColumn14);
            _setFontForComponent(_nsTableView3.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView3.table().setRowHeight(19);
        }

        _eoTableAssociation2.bindAspect(com.webobjects.eointerface.EOAssociation.SourceAspect, _eoDisplayGroup3, "");
        _eoTableAssociation2.setSortsByColumnOrder(true);
        _eoTableAssociation2.establishConnection();

        if (_replacedObjects.objectForKey("_eoDisplayGroup3") == null) {
            _eoDisplayGroup3.setValidatesChangesImmediately(false);
            _eoDisplayGroup3.setFetchesOnLoad(false);
            _eoDisplayGroup3.setUsesOptimisticRefresh(false);
            _eoDisplayGroup3.setSelectsFirstObjectAfterFetch(true);
        }

        if (_replacedObjects.objectForKey("_eoDisplayGroup3") == null) {
            _connect(_eoDisplayGroup3, _eoDataSource3, "dataSource");
        }

        if (_replacedObjects.objectForKey("_eoDataSource3") == null) {
            _connect(_eoDataSource3, _eoEditingContext0, "editingContext");
        }

        _nsNumberFormatter5.setLocalizesPattern(true);
        _eoTableAssociation1.bindAspect(com.webobjects.eointerface.EOAssociation.SourceAspect, _eoDisplayGroup2, "");
        _eoTableAssociation1.setSortsByColumnOrder(true);
        _eoTableAssociation1.establishConnection();
        _nsNumberFormatter4.setLocalizesPattern(true);
        _eoTableColumnAssociation9.bindAspect(com.webobjects.eointerface.EOAssociation.ValueAspect, _eoDisplayGroup2, "mapSeuil");
        if (_eoTableColumnAssociation9.canSupportValueFormatter()) { _eoTableColumnAssociation9.setValueFormatter(_nsNumberFormatter4); }
        _eoTableColumnAssociation9.establishConnection();
        _eoTableColumn9.setMinWidth(36);
        _eoTableColumn9.setMaxWidth(1000);
        _eoTableColumn9.setPreferredWidth(57);
        _eoTableColumn9.setWidth(57);
        _eoTableColumn9.setResizable(true);
        _eoTableColumn9.setHeaderValue("Seuil ");
        _nsNumberFormatter3.setLocalizesPattern(true);
        _eoTableColumnAssociation8.bindAspect(com.webobjects.eointerface.EOAssociation.ValueAspect, _eoDisplayGroup2, "mapGroupeReel");
        if (_eoTableColumnAssociation8.canSupportValueFormatter()) { _eoTableColumnAssociation8.setValueFormatter(_nsNumberFormatter3); }
        _eoTableColumnAssociation8.establishConnection();
        _eoTableColumn8.setMinWidth(10);
        _eoTableColumn8.setMaxWidth(1000);
        _eoTableColumn8.setPreferredWidth(55);
        _eoTableColumn8.setWidth(55);
        _eoTableColumn8.setResizable(true);
        _eoTableColumn8.setHeaderValue("Gr Reels");
        _eoTableColumnAssociation7.bindAspect(com.webobjects.eointerface.EOAssociation.ValueAspect, _eoDisplayGroup2, "mapLibelle");
        _eoTableColumnAssociation7.establishConnection();
        _eoTableColumn7.setMinWidth(10);
        _eoTableColumn7.setMaxWidth(1000);
        _eoTableColumn7.setPreferredWidth(280);
        _eoTableColumn7.setWidth(280);
        _eoTableColumn7.setResizable(true);
        _eoTableColumn7.setHeaderValue("Libelle Ap");

        if (_replacedObjects.objectForKey("_nsTableView2") == null) {
            _nsTableView2.table().addColumn(_eoTableColumn7);
            _nsTableView2.table().addColumn(_eoTableColumn6);
            _nsTableView2.table().addColumn(_eoTableColumn8);
            _nsTableView2.table().addColumn(_eoTableColumn9);
            _setFontForComponent(_nsTableView2.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView2.table().setRowHeight(19);
        }

        _eoTableColumn6.setMinWidth(10);
        _eoTableColumn6.setMaxWidth(1000);
        _eoTableColumn6.setPreferredWidth(58);
        _eoTableColumn6.setWidth(58);
        _eoTableColumn6.setResizable(true);
        _eoTableColumn6.setHeaderValue("Gr Prevus");
        _eoTableColumnAssociation6.bindAspect(com.webobjects.eointerface.EOAssociation.ValueAspect, _eoDisplayGroup2, "mapGroupePrevu");
        if (_eoTableColumnAssociation6.canSupportValueFormatter()) { _eoTableColumnAssociation6.setValueFormatter(_nsNumberFormatter5); }
        _eoTableColumnAssociation6.establishConnection();

        if (_replacedObjects.objectForKey("_eoDisplayGroup2") == null) {
            _eoDisplayGroup2.setValidatesChangesImmediately(false);
            _eoDisplayGroup2.setFetchesOnLoad(false);
            _eoDisplayGroup2.setUsesOptimisticRefresh(false);
            _eoDisplayGroup2.setSelectsFirstObjectAfterFetch(true);
        }

        if (_replacedObjects.objectForKey("_eoDisplayGroup2") == null) {
            _connect(_eoDisplayGroup2, _eoDataSource2, "dataSource");
        }

        if (_replacedObjects.objectForKey("_eoDataSource2") == null) {
            _connect(_eoDataSource2, _eoEditingContext0, "editingContext");
        }

        _eoTableAssociation0.bindAspect(com.webobjects.eointerface.EOAssociation.SourceAspect, _eoDisplayGroup1, "");
        _eoTableAssociation0.setSortsByColumnOrder(true);
        _eoTableAssociation0.establishConnection();
        
        _eoTableColumnAssociation5.bindAspect(com.webobjects.eointerface.EOAssociation.ValueAspect, _eoDisplayGroup1, "ggrpDateFin");
        if (_eoTableColumnAssociation5.canSupportValueFormatter()) { _eoTableColumnAssociation5.setValueFormatter(_nsNumberFormatter2); }
        _eoTableColumnAssociation5.establishConnection();
        _eoTableColumn5.setMinWidth(67);
        _eoTableColumn5.setMaxWidth(1000);
        _eoTableColumn5.setPreferredWidth(120);
        _eoTableColumn5.setWidth(120);
        _eoTableColumn5.setResizable(true);
        _eoTableColumn5.setHeaderValue("Fin Validit\u00e9");
        if ((_eoTableColumn5.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn5.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        	_eoTableColumn5.setCellRenderer(renderer);
        }
        
        _eoTableColumnAssociation4.bindAspect(com.webobjects.eointerface.EOAssociation.ValueAspect, _eoDisplayGroup1, "ggrpDateDebut");
        if (_eoTableColumnAssociation4.canSupportValueFormatter()) { _eoTableColumnAssociation4.setValueFormatter(_nsNumberFormatter1); }
        _eoTableColumnAssociation4.establishConnection();
        _eoTableColumn4.setMinWidth(10);
        _eoTableColumn4.setMaxWidth(1000);
        _eoTableColumn4.setPreferredWidth(117);
        _eoTableColumn4.setWidth(117);
        _eoTableColumn4.setResizable(true);
        _eoTableColumn4.setHeaderValue("D\u00e9but Validit\u00e9");
        if ((_eoTableColumn4.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn4.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        	_eoTableColumn4.setCellRenderer(renderer);
        }
        _eoTableColumnAssociation3.bindAspect(com.webobjects.eointerface.EOAssociation.ValueAspect, _eoDisplayGroup1, "ggrpLibelle");
        _eoTableColumnAssociation3.establishConnection();
        _eoTableColumn3.setMinWidth(10);
        _eoTableColumn3.setMaxWidth(1000);
        _eoTableColumn3.setPreferredWidth(111);
        _eoTableColumn3.setWidth(111);
        _eoTableColumn3.setResizable(true);
        _eoTableColumn3.setHeaderValue("Libelle");
        _nsNumberFormatter0.setLocalizesPattern(true);
        _eoTableColumnAssociation2.bindAspect(com.webobjects.eointerface.EOAssociation.ValueAspect, _eoDisplayGroup1, "ggrpMaxCapacite");
        if (_eoTableColumnAssociation2.canSupportValueFormatter()) { _eoTableColumnAssociation2.setValueFormatter(_nsNumberFormatter0); }
        _eoTableColumnAssociation2.establishConnection();
        _eoTableColumn2.setMinWidth(10);
        _eoTableColumn2.setMaxWidth(1000);
        _eoTableColumn2.setPreferredWidth(55);
        _eoTableColumn2.setWidth(55);
        _eoTableColumn2.setResizable(true);
        _eoTableColumn2.setHeaderValue("Cap. Max");

        if (_replacedObjects.objectForKey("_nsTableView1") == null) {
            _nsTableView1.table().addColumn(_eoTableColumn1);
            _nsTableView1.table().addColumn(_eoTableColumn2);
            _nsTableView1.table().addColumn(_eoTableColumn3);
            _nsTableView1.table().addColumn(_eoTableColumn4);
            _nsTableView1.table().addColumn(_eoTableColumn5);
            _setFontForComponent(_nsTableView1.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView1.table().setRowHeight(19);
        }

        _eoTableColumn1.setMinWidth(10);
        _eoTableColumn1.setMaxWidth(1000);
        _eoTableColumn1.setPreferredWidth(110);
        _eoTableColumn1.setWidth(110);
        _eoTableColumn1.setResizable(true);
        _eoTableColumn1.setHeaderValue("Code");
        _eoTableColumnAssociation1.bindAspect(com.webobjects.eointerface.EOAssociation.ValueAspect, _eoDisplayGroup1, "ggrpCode");
        _eoTableColumnAssociation1.establishConnection();

        if (_replacedObjects.objectForKey("_eoDisplayGroup1") == null) {
            _eoDisplayGroup1.setValidatesChangesImmediately(false);
            _eoDisplayGroup1.setFetchesOnLoad(false);
            _eoDisplayGroup1.setUsesOptimisticRefresh(false);
            _eoDisplayGroup1.setSelectsFirstObjectAfterFetch(true);
        }

        if (_replacedObjects.objectForKey("_eoDisplayGroup1") == null) {
            _connect(_eoDisplayGroup1, _eoDataSource1, "dataSource");
        }

        if (_replacedObjects.objectForKey("_eoDataSource1") == null) {
            _connect(_eoDataSource1, _eoEditingContext0, "editingContext");
        }

        if (_replacedObjects.objectForKey("_eoDataSource0") == null) {
            _connect(_eoDataSource0, _eoEditingContext0, "editingContext");
        }

        if (_replacedObjects.objectForKey("_eoDisplayGroup0") == null) {
            _connect(_eoDisplayGroup0, _eoDataSource0, "dataSource");
        }

        if (_replacedObjects.objectForKey("_eoDisplayGroup0") == null) {
            _eoDisplayGroup0.setValidatesChangesImmediately(false);
            _eoDisplayGroup0.setFetchesOnLoad(false);
            _eoDisplayGroup0.setUsesOptimisticRefresh(false);
            _eoDisplayGroup0.setSelectsFirstObjectAfterFetch(true);
        }

        _eoTableColumnAssociation0.bindAspect(com.webobjects.eointerface.EOAssociation.ValueAspect, _eoDisplayGroup0, "gcolLibelle");
        _eoTableColumnAssociation0.establishConnection();
        _eoTableColumn0.setMinWidth(95);
        _eoTableColumn0.setMaxWidth(1000);
        _eoTableColumn0.setPreferredWidth(166);
        _eoTableColumn0.setWidth(166);
        _eoTableColumn0.setResizable(true);
        _eoTableColumn0.setHeaderValue("Libelle Collection");

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _nsTableView0.table().addColumn(_eoTableColumn0);
            _nsTableView0.table().addColumn(_eoTableColumn15);
            _nsTableView0.table().addColumn(_eoTableColumn16);
            _setFontForComponent(_nsTableView0.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView0.table().setRowHeight(19);
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
            _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        }

        _setFontForComponent(_nsTextField0, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Diff\u00e9rents types d'AP par seuil de groupe");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsTextField0.setSize(237, 14);
        _nsTextField0.setLocation(5, 9);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsTextField0);
        _nsButton0.setSize(137, 29);
        _nsButton0.setLocation(44, 168);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsButton0);
        _nsTableView0.setSize(231, 159);
        _nsTableView0.setLocation(7, 219);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsTableView0, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsTableView0);
        _nsTableView1.setSize(302, 159);
        _nsTableView1.setLocation(296, 224);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsTableView1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsTableView1);
        _nsTableView2.setSize(480, 163);
        _nsTableView2.setLocation(292, 34);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsTableView2, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsTableView2);
        _nsTextField1.setSize(222, 17);
        _nsTextField1.setLocation(290, 16);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsTextField1);
        _nsTextField2.setSize(318, 17);
        _nsTextField2.setLocation(294, 205);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsTextField2);
        _nsTextField3.setSize(85, 17);
        _nsTextField3.setLocation(5, 199);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsTextField3);
        _nsButton1.setSize(24, 22);
        _nsButton1.setLocation(217, 189);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsButton1);
        _nsCustomView0.setSize(231, 136);
        _nsCustomView0.setLocation(7, 26);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsCustomView0);
        _nsButton2.setSize(28, 26);
        _nsButton2.setLocation(777, 32);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsButton2);
        _nsButton3.setSize(28, 26);
        _nsButton3.setLocation(777, 66);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsButton3);
        _nsButton4.setSize(24, 22);
        _nsButton4.setLocation(187, 189);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsButton4);
        _nsTableView3.setSize(198, 134);
        _nsTableView3.setLocation(606, 249);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsTableView3, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsTableView3);
        _nsButton5.setSize(24, 22);
        _nsButton5.setLocation(714, 222);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsButton5, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsButton5);
        _nsButton6.setSize(24, 22);
        _nsButton6.setLocation(744, 222);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsButton6, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsButton6);
        _nsButton12.setSize(84, 17);
        _nsButton12.setLocation(690, 11);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsButton12, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsButton12);
        _popup0.setSize(171, 26);
        _popup0.setLocation(508, 7);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_popup0, EOViewLayout.MinYMargin);
        _nsBox0.add(_popup0);
        _nsTextField4.setSize(122, 17);
        _nsTextField4.setLocation(604, 227);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsTextField4);
        _nsButton7.setSize(28, 26);
        _nsButton7.setLocation(777, 102);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsButton7, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsButton7);
        _nsButton9.setSize(24, 22);
        _nsButton9.setLocation(781, 222);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsButton9, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsButton9);
        _nsButton8.setSize(24, 22);
        _nsButton8.setLocation(265, 266);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsButton8, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsButton8);
        _nsButton10.setSize(24, 22);
        _nsButton10.setLocation(265, 236);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsButton10, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsButton10);
        _nsButton11.setSize(24, 22);
        _nsButton11.setLocation(265, 296);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsButton11, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsButton11);
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsBox0.setSize(814, 402);
        _nsBox0.setLocation(7, 7);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox0);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(829, 416);
            _eoFrame0.setTitle("Window");
            _eoFrame0.setLocation(294, 357);
            _eoFrame0.setSize(829, 416);
        }
    }
}
