// _CreationCollection_EOArchive.java
// Generated by EnterpriseObjects palette at vendredi 29 janvier 2010 15 h 11 Europe/Paris

package org.cocktail.groupescol.client;

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _CreationCollection_EOArchive extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField10, _nsTextField11, _nsTextField12, _nsTextField13, _nsTextField14, _nsTextField2, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6, _nsTextField7, _nsTextField8, _nsTextField9;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1;
    javax.swing.JButton _nsButton0, _nsButton1;
    javax.swing.JCheckBox _nsButton2;
    javax.swing.JPanel _nsView0;

    public _CreationCollection_EOArchive(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsTextField14 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1312111");
        _nsTextField13 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField13121");
        _nsTextField12 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1312");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tInfos")) != null)) {
            _nsTextField11 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField11");
        } else {
            _nsTextField11 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "lDebutVal")) != null)) {
            _nsTextField10 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField10");
        } else {
            _nsTextField10 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField131211");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "lPrefixGrp")) != null)) {
            _nsTextField9 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField9");
        } else {
            _nsTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1311");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "lNbGrp")) != null)) {
            _nsTextField8 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField8");
        } else {
            _nsTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField131");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "lLibelleCol")) != null)) {
            _nsTextField7 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField7");
        } else {
            _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField13");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bAnnuler")) != null)) {
            _nsButton1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton1");
        } else {
            _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Annuler"), "NSButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "bCreer")) != null)) {
            _nsButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton0");
        } else {
            _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cr\u00e9er"), "NSButton1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tFinVal")) != null)) {
            _nsTextField6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField6");
        } else {
            _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1212");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tDebutVal")) != null)) {
            _nsTextField5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField5");
        } else {
            _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1211");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "cBoquante")) != null)) {
            _nsButton2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton2");
        } else {
            _nsButton2 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Bloquante"), "NSButton4");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tCapaInt")) != null)) {
            _nsTextField4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField4");
        } else {
            _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField121");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tCapa")) != null)) {
            _nsTextField3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField3");
        } else {
            _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField12");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tPrefixGrp")) != null)) {
            _nsTextField2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField2");
        } else {
            _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tNbGrp")) != null)) {
            _nsTextField1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField1");
        } else {
            _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tLibelleCol")) != null)) {
            _nsTextField0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField0");
        } else {
            _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        }

        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "component")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "MainWindow");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_nsTextField11") == null) {
            _connect(_owner(), _nsTextField11, "tInfos");
        }

        if (_replacedObjects.objectForKey("_nsTextField10") == null) {
            _connect(_owner(), _nsTextField10, "lDebutVal");
        }

        if (_replacedObjects.objectForKey("_nsTextField9") == null) {
            _connect(_owner(), _nsTextField9, "lPrefixGrp");
        }

        if (_replacedObjects.objectForKey("_nsTextField8") == null) {
            _connect(_owner(), _nsTextField8, "lNbGrp");
        }

        if (_replacedObjects.objectForKey("_nsTextField7") == null) {
            _connect(_owner(), _nsTextField7, "lLibelleCol");
        }

        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "annuler", _nsButton1), ""));

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _connect(_owner(), _nsButton1, "bAnnuler");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "creerCollection", _nsButton0), ""));

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _connect(_owner(), _nsButton0, "bCreer");
        }

        if (_replacedObjects.objectForKey("_nsTextField6") == null) {
            _connect(_owner(), _nsTextField6, "tFinVal");
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _connect(_owner(), _nsTextField5, "tDebutVal");
        }

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _connect(_owner(), _nsButton2, "cBoquante");
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _connect(_owner(), _nsTextField4, "tCapaInt");
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _connect(_owner(), _nsTextField3, "tCapa");
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _connect(_owner(), _nsTextField2, "tPrefixGrp");
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_owner(), _nsTextField1, "tNbGrp");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "component");
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _connect(_owner(), _nsTextField0, "tLibelleCol");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsTextField14, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField14.setEditable(false);
        _nsTextField14.setOpaque(false);
        _nsTextField14.setText("Fin validit\u00e9");
        _nsTextField14.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField14.setSelectable(false);
        _nsTextField14.setEnabled(true);
        _nsTextField14.setBorder(null);
        _setFontForComponent(_nsTextField13, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField13.setEditable(false);
        _nsTextField13.setOpaque(false);
        _nsTextField13.setText("Capacite intermidiaire");
        _nsTextField13.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField13.setSelectable(false);
        _nsTextField13.setEnabled(true);
        _nsTextField13.setBorder(null);
        _setFontForComponent(_nsTextField12, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField12.setEditable(false);
        _nsTextField12.setOpaque(false);
        _nsTextField12.setText("Capacite");
        _nsTextField12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField12.setSelectable(false);
        _nsTextField12.setEnabled(true);
        _nsTextField12.setBorder(null);

        if (_replacedObjects.objectForKey("_nsTextField11") == null) {
            _setFontForComponent(_nsTextField11, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField11.setEditable(true);
            _nsTextField11.setOpaque(true);
            _nsTextField11.setText("");
            _nsTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            _nsTextField11.setSelectable(true);
            _nsTextField11.setEnabled(true);
            _nsTextField11.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField10") == null) {
            _setFontForComponent(_nsTextField10, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField10.setEditable(false);
            _nsTextField10.setOpaque(false);
            _nsTextField10.setText("D\u00e9but validit\u00e9");
            _nsTextField10.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField10.setSelectable(false);
            _nsTextField10.setEnabled(true);
            _nsTextField10.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField9") == null) {
            _setFontForComponent(_nsTextField9, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField9.setEditable(false);
            _nsTextField9.setOpaque(false);
            _nsTextField9.setText("Pr\u00e9fix groupe");
            _nsTextField9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField9.setSelectable(false);
            _nsTextField9.setEnabled(true);
            _nsTextField9.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField8") == null) {
            _setFontForComponent(_nsTextField8, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField8.setEditable(false);
            _nsTextField8.setOpaque(false);
            _nsTextField8.setText("Nombre de groupes");
            _nsTextField8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField8.setSelectable(false);
            _nsTextField8.setEnabled(true);
            _nsTextField8.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField7") == null) {
            _setFontForComponent(_nsTextField7, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField7.setEditable(false);
            _nsTextField7.setOpaque(false);
            _nsTextField7.setText("Libelle collection");
            _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField7.setSelectable(false);
            _nsTextField7.setEnabled(true);
            _nsTextField7.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
            _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
            _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsTextField6") == null) {
            _setFontForComponent(_nsTextField6, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField6.setEditable(true);
            _nsTextField6.setOpaque(true);
            _nsTextField6.setText("");
            _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField6.setSelectable(true);
            _nsTextField6.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _setFontForComponent(_nsTextField5, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField5.setEditable(true);
            _nsTextField5.setOpaque(true);
            _nsTextField5.setText("");
            _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField5.setSelectable(true);
            _nsTextField5.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _setFontForComponent(_nsButton2, "Lucida Grande", 12, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _setFontForComponent(_nsTextField4, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField4.setEditable(true);
            _nsTextField4.setOpaque(true);
            _nsTextField4.setText("");
            _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField4.setSelectable(true);
            _nsTextField4.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _setFontForComponent(_nsTextField3, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField3.setEditable(true);
            _nsTextField3.setOpaque(true);
            _nsTextField3.setText("");
            _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField3.setSelectable(true);
            _nsTextField3.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _setFontForComponent(_nsTextField2, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField2.setEditable(true);
            _nsTextField2.setOpaque(true);
            _nsTextField2.setText("");
            _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField2.setSelectable(true);
            _nsTextField2.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _setFontForComponent(_nsTextField1, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField1.setEditable(true);
            _nsTextField1.setOpaque(true);
            _nsTextField1.setText("");
            _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField1.setSelectable(true);
            _nsTextField1.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField0.setEditable(true);
            _nsTextField0.setOpaque(true);
            _nsTextField0.setText("");
            _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField0.setSelectable(true);
            _nsTextField0.setEnabled(true);
        }

        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _nsTextField0.setSize(142, 22);
        _nsTextField0.setLocation(15, 65);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField0);
        _nsTextField1.setSize(122, 22);
        _nsTextField1.setLocation(174, 65);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField1);
        _nsTextField2.setSize(114, 22);
        _nsTextField2.setLocation(389, 65);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField2);
        _nsTextField3.setSize(122, 22);
        _nsTextField3.setLocation(174, 116);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField3);
        _nsTextField4.setSize(122, 22);
        _nsTextField4.setLocation(174, 169);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField4);
        _nsTextField5.setSize(114, 22);
        _nsTextField5.setLocation(389, 115);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField5);
        _nsTextField6.setSize(114, 22);
        _nsTextField6.setLocation(389, 169);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField6);
        _nsTextField7.setSize(148, 14);
        _nsTextField7.setLocation(12, 46);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField7);
        _nsTextField8.setSize(128, 14);
        _nsTextField8.setLocation(171, 47);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField8, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField8);
        _nsTextField9.setSize(120, 14);
        _nsTextField9.setLocation(386, 47);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField9, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField9);
        _nsTextField12.setSize(128, 14);
        _nsTextField12.setLocation(171, 100);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField12, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField12);
        _nsTextField13.setSize(128, 14);
        _nsTextField13.setLocation(171, 152);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField13, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField13);
        _nsTextField10.setSize(120, 14);
        _nsTextField10.setLocation(386, 97);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField10, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField10);
        _nsTextField14.setSize(120, 14);
        _nsTextField14.setLocation(386, 151);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField14, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField14);
        _nsButton1.setSize(83, 26);
        _nsButton1.setLocation(423, 210);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsButton1);
        _nsButton0.setSize(77, 26);
        _nsButton0.setLocation(299, 210);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsButton0);
        _nsButton2.setSize(85, 17);
        _nsButton2.setLocation(298, 120);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsButton2);
        _nsTextField11.setSize(293, 17);
        _nsTextField11.setLocation(109, 8);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField11, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField11);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(530, 246);
        _nsBox1.setLocation(2, 2);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsBox0.setSize(534, 250);
        _nsBox0.setLocation(5, 1);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox0);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(552, 265);
            _eoFrame0.setTitle("Window");
            _eoFrame0.setLocation(177, 539);
            _eoFrame0.setSize(552, 265);
        }
    }
}
